import type { Reference } from "@/lib/references";

/*
  Foundational work the books cite by bare identifier or name only. Every arXiv identifier
  here was checked against its abstract page — the title returned had to match the paper
  meant. Entries here also override a harvested link with the same identifier, which is how
  `arXiv:2303.04137` in the prose becomes a result you can find by typing its name.
*/
export const CURATED: Reference[] = [
  {
    name: "Diffusion Policy",
    aliases: ["diffusion policy", "diffusion policies", "action diffusion"],
    kind: "paper",
    url: "https://arxiv.org/abs/2303.04137",
    note: "Visuomotor policy learning via action diffusion",
    context: "Foundational reference",
  },
  {
    name: "ACT / ALOHA",
    aliases: ["act", "aloha", "action chunking transformer", "action chunking"],
    kind: "paper",
    url: "https://arxiv.org/abs/2304.13705",
    note: "Action chunking transformer and the low-cost bimanual rig",
    context: "Foundational reference",
  },
  {
    name: "OpenVLA",
    aliases: ["openvla", "open vla"],
    kind: "paper",
    url: "https://arxiv.org/abs/2406.09246",
    note: "Open-source 7B vision-language-action model",
    context: "Foundational reference",
  },
  {
    name: "π0",
    aliases: ["pi0", "pi zero", "pi 0", "physical intelligence pi0"],
    kind: "paper",
    url: "https://arxiv.org/abs/2410.24164",
    note: "Vision-language-action flow model for general robot control",
    context: "Foundational reference",
  },
  {
    name: "UMI",
    aliases: ["umi", "universal manipulation interface"],
    kind: "system",
    url: "https://arxiv.org/abs/2402.10329",
    note: "Handheld gripper for in-the-wild demonstrations without a robot",
    context: "Foundational reference",
  },
  {
    name: "Open X-Embodiment",
    aliases: ["open x-embodiment", "open x embodiment", "oxe", "rt-x"],
    kind: "dataset",
    url: "https://arxiv.org/abs/2310.08864",
    note: "Pooled cross-embodiment corpus and the RT-X models",
    context: "Foundational reference",
  },
  {
    name: "GR00T N1",
    aliases: ["gr00t", "groot", "gr00t n1", "groot n1"],
    kind: "system",
    url: "https://arxiv.org/abs/2503.14734",
    note: "Open foundation model for generalist humanoid robots",
    context: "Foundational reference",
  },
  {
    name: "emg2pose",
    aliases: ["emg2pose", "emg 2 pose"],
    kind: "dataset",
    url: "https://arxiv.org/abs/2412.02725",
    note: "301 participants, 716 hours of wrist sEMG with hand pose labels",
    context: "Foundational reference",
  },
  {
    name: "RT-1",
    aliases: ["rt-1", "robotics transformer 1", "robotics transformer"],
    kind: "paper",
    url: "https://arxiv.org/abs/2212.06817",
    note: "Transformer policy trained on large-scale real robot action data",
    context: "Foundational reference",
  },
  {
    name: "RT-2",
    aliases: ["rt-2", "robotics transformer 2"],
    kind: "paper",
    url: "https://arxiv.org/abs/2307.15818",
    note: "Vision-language model fine-tuned to emit robot actions; the VLA template",
    context: "Foundational reference",
  },
  {
    name: "Gemini Robotics",
    aliases: ["gemini robotics", "gemini robotics er"],
    kind: "system",
    url: "https://arxiv.org/abs/2503.20020",
    note: "DeepMind frontier VLA and embodied reasoning model family",
    context: "Foundational reference",
  },
  {
    name: "Mobile ALOHA",
    aliases: ["mobile aloha", "aloha"],
    kind: "system",
    url: "https://arxiv.org/abs/2401.02117",
    note: "Low-cost bimanual teleop rig with a mobile base",
    context: "Foundational reference",
  },
  {
    name: "DROID",
    aliases: ["droid", "droid dataset"],
    kind: "dataset",
    url: "https://arxiv.org/abs/2403.12945",
    note: "76k trajectories, 350 hours, standardised Franka rig, 13 institutions",
    context: "Foundational reference",
  },
  {
    name: "BridgeData V2",
    aliases: ["bridgedata v2", "bridge data v2", "bridge v2"],
    kind: "dataset",
    url: "https://arxiv.org/abs/2308.12952",
    note: "60k WidowX trajectories across 24 environments",
    context: "Foundational reference",
  },
  {
    name: "RH20T",
    aliases: ["rh20t"],
    kind: "dataset",
    url: "https://arxiv.org/abs/2307.00595",
    note: "110k contact-rich sequences with 6-DoF force/torque at 100 Hz",
    context: "Foundational reference",
  },
  {
    name: "BEHAVIOR-1K",
    aliases: ["behavior", "behavior-1k", "behavior 1k", "omnigibson"],
    kind: "benchmark",
    url: "https://arxiv.org/abs/2403.09227",
    note: "1,000 household activities in a simulator with fluids, cloth and heat",
    context: "Foundational reference",
  },
  {
    name: "LIBERO",
    aliases: ["libero"],
    kind: "benchmark",
    url: "https://arxiv.org/abs/2306.03310",
    note: "Lifelong robot learning suite used as the default VLA leaderboard",
    context: "Foundational reference",
  },
  {
    name: "SIMPLER",
    aliases: ["simpler", "simpler-env", "simpler env"],
    kind: "benchmark",
    url: "https://arxiv.org/abs/2405.05941",
    note: "Simulated evaluation matched to real hardware policy rankings",
    context: "Foundational reference",
  },
  {
    name: "Ego4D",
    aliases: ["ego4d", "ego 4d"],
    kind: "dataset",
    url: "https://arxiv.org/abs/2110.07058",
    note: "3,000 hours of egocentric human activity video",
    context: "Foundational reference",
  },
  {
    name: "Ego-Exo4D",
    aliases: ["ego-exo4d", "ego exo 4d", "egoexo4d"],
    kind: "dataset",
    url: "https://arxiv.org/abs/2311.18259",
    note: "1,286 hours of synchronised egocentric and third-person video",
    context: "Foundational reference",
  },
  {
    name: "DexUMI",
    aliases: ["dexumi", "dex umi"],
    kind: "system",
    url: "https://arxiv.org/abs/2505.21864",
    note: "Wearable exoskeleton extending UMI to multi-fingered hands",
    context: "Foundational reference",
  },
  {
    name: "CrossFormer",
    aliases: ["crossformer", "cross former"],
    kind: "paper",
    url: "https://arxiv.org/abs/2408.11812",
    note: "Single cross-embodiment policy over manipulation, navigation and flight",
    context: "Foundational reference",
  },
  {
    name: "TWIST",
    aliases: ["twist", "teleoperated whole-body imitation system"],
    kind: "system",
    url: "https://arxiv.org/abs/2505.02833",
    note: "Whole-body humanoid teleoperation and imitation system",
    context: "Foundational reference",
  },
  {
    name: "ToddlerBot",
    aliases: ["toddlerbot", "toddler bot"],
    kind: "system",
    url: "https://arxiv.org/abs/2502.00893",
    note: "Open-source 3D-printed humanoid for loco-manipulation research",
    context: "Foundational reference",
  },
  {
    name: "TidyBot++",
    aliases: ["tidybot++", "tidybot"],
    kind: "system",
    url: "https://arxiv.org/abs/2412.10447",
    note: "Open-source holonomic mobile manipulator for robot learning",
    context: "Foundational reference",
  },
  {
    name: "Open-TeleVision",
    aliases: ["open-television", "open television", "opentelevision"],
    kind: "system",
    url: "https://arxiv.org/abs/2407.01512",
    note: "VR teleoperation with immersive active stereo visual feedback",
    context: "Foundational reference",
  },
  {
    name: "AnyTeleop",
    aliases: ["anyteleop", "any teleop"],
    kind: "system",
    url: "https://arxiv.org/abs/2307.04577",
    note: "Vision-based teleoperation across arm and dexterous hand embodiments",
    context: "Foundational reference",
  },
  {
    name: "ACE",
    aliases: ["ace", "ace exoskeleton"],
    kind: "system",
    url: "https://arxiv.org/abs/2408.11805",
    note: "Low-cost visual exoskeleton for dexterous teleoperation",
    context: "Foundational reference",
  },
  {
    name: "HOMIE",
    aliases: ["homie"],
    kind: "system",
    url: "https://arxiv.org/abs/2502.13013",
    note: "Isomorphic exoskeleton cockpit for humanoid loco-manipulation",
    context: "Foundational reference",
  },
  {
    name: "RISE",
    aliases: ["rise", "rise policy"],
    kind: "paper",
    url: "https://arxiv.org/abs/2404.12281",
    note: "3D point-cloud imitation baseline used in force-conditioning ablations",
    context: "Foundational reference",
  },
  {
    name: "Feel the Force",
    aliases: ["feel the force", "ftf"],
    kind: "paper",
    url: "https://arxiv.org/abs/2506.01944",
    note: "Contact-force-instrumented human demonstrations for manipulation",
    context: "Foundational reference",
  },
  {
    name: "Sparsh",
    aliases: ["sparsh"],
    kind: "paper",
    url: "https://arxiv.org/abs/2410.24090",
    note: "Self-supervised representations for vision-based tactile sensors",
    context: "Foundational reference",
  },
  {
    name: "FAST",
    aliases: ["fast", "fast action tokenizer"],
    kind: "paper",
    url: "https://arxiv.org/abs/2501.09747",
    note: "Action tokenisation scheme used by Physical Intelligence policies",
    context: "Foundational reference",
  },
  {
    name: "ASAP",
    aliases: ["asap"],
    kind: "paper",
    url: "https://arxiv.org/abs/2502.01143",
    note: "Sim-real physics alignment for agile humanoid whole-body skills",
    context: "Foundational reference",
  },
  {
    name: "DrEureka",
    aliases: ["dreureka", "dr eureka"],
    kind: "paper",
    url: "https://arxiv.org/abs/2406.01967",
    note: "LLM-guided reward and domain-randomisation design for sim-to-real",
    context: "Foundational reference",
  },
  {
    name: "Gen2Act",
    aliases: ["gen2act", "gen 2 act"],
    kind: "paper",
    url: "https://arxiv.org/abs/2409.16283",
    note: "Generated human video as an intermediate for robot manipulation",
    context: "Foundational reference",
  },
  {
    name: "DreamGen",
    aliases: ["dreamgen", "groot-dreams"],
    kind: "paper",
    url: "https://arxiv.org/abs/2505.12705",
    note: "Synthetic robot trajectories from video world models",
    context: "Foundational reference",
  },
  {
    name: "NVIDIA Cosmos",
    aliases: ["cosmos", "nvidia cosmos", "cosmos-predict"],
    kind: "system",
    url: "https://arxiv.org/abs/2501.03575",
    note: "World foundation model platform used for synthetic robot data",
    context: "Foundational reference",
  },
  {
    name: "V-JEPA 2",
    aliases: ["v-jepa 2", "vjepa2", "v jepa 2"],
    kind: "paper",
    url: "https://arxiv.org/abs/2506.09985",
    note: "Video world model trained on 1M+ hours plus 62 hours of robot data",
    context: "Foundational reference",
  },
  {
    name: "Isaac Lab (Orbit)",
    aliases: ["isaac lab", "orbit", "isaac sim"],
    kind: "system",
    url: "https://arxiv.org/abs/2301.04195",
    note: "GPU-accelerated simulation framework underlying Isaac Lab",
    context: "Foundational reference",
  },
  {
    name: "ManiSkill3",
    aliases: ["maniskill3", "maniskill", "mani skill 3"],
    kind: "benchmark",
    url: "https://arxiv.org/abs/2410.00425",
    note: "GPU-parallel simulation and rendering for manipulation benchmarks",
    context: "Foundational reference",
  },
  {
    name: "MuJoCo Playground",
    aliases: ["mujoco playground", "mjx playground"],
    kind: "system",
    url: "https://arxiv.org/abs/2502.08844",
    note: "MJX/JAX environment suite for locomotion and dexterous sim-to-real",
    context: "Foundational reference",
  },
  {
    name: "PARTNR",
    aliases: ["partnr"],
    kind: "benchmark",
    url: "https://arxiv.org/abs/2411.00081",
    note: "Benchmark for planning and reasoning in human-robot collaboration",
    context: "Foundational reference",
  },
  {
    name: "Neural Jacobian Fields",
    aliases: ["neural jacobian fields", "jacobian fields"],
    kind: "paper",
    url: "https://arxiv.org/abs/2407.08722",
    note: "Robot self-modelling and control learned from monocular video",
    context: "Foundational reference",
  },
  {
    name: "Splat-Nav",
    aliases: ["splat-nav", "splatnav", "splat nav"],
    kind: "system",
    url: "https://arxiv.org/abs/2403.02751",
    note: "Real-time navigation and planning inside Gaussian Splatting maps",
    context: "Foundational reference",
  },
  {
    name: "3D Gaussian Splatting",
    aliases: ["3d gaussian splatting", "gaussian splatting", "3dgs"],
    kind: "paper",
    url: "https://arxiv.org/abs/2308.04079",
    note: "Scene representation underlying real-to-sim robotics reconstruction",
    context: "Foundational reference",
  },
  {
    name: "LoRA",
    aliases: ["lora", "low-rank adaptation"],
    kind: "paper",
    url: "https://arxiv.org/abs/2106.09685",
    note: "Parameter-efficient fine-tuning used for VLA post-training",
    context: "Foundational reference",
  },
  {
    name: "emg2qwerty",
    aliases: ["emg2qwerty", "emg 2 qwerty"],
    kind: "dataset",
    url: "https://arxiv.org/abs/2410.20081",
    note: "108-user surface EMG touch-typing corpus with baselines",
    context: "Foundational reference",
  },
];
